# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_auto_20180124_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apptoken',
            options={'verbose_name': 'App Token', 'verbose_name_plural': 'App Tokens'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'User Token', 'verbose_name_plural': 'User Tokens'},
        ),
    ]
