# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_auto_20180124_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptoken',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apptoken',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
